---
apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: fizzbuzz-service   # Name of the resource
spec:
  type: NodePort                 # A port is opened on each node in your cluster via Kube proxy.
  ports:                         # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8080
  - name: http
    port: 8001
    targetPort: 8000
  selector:
    app: fizzbuzz        # Map any pod with label `app=fizzbuzz` to this service
