---
apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: fizzbuzz           # Name of the Kubernetes resource
spec:
  replicas: 3                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: fizzbuzz        # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: fizzbuzz
    spec:                        # Spec for the container which will run in the Pod
      containers:
      - name: fizzbuzz
        image: santoshr1016/fizzbuzz:v0.0.3
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000  # Should match the port number that the application listens on
